### ISSUE TITLE
Compilation failed on Xubuntu 22.04

### ISSUE THREAD

**Issue by Srandista** [lincity-ng/lincity-ng#145]
Hello.
I tried to compile latest build on Xubuntu 22.04, but compilation failed on following step:

```[  0%] Building CXX object src/gui/CMakeFiles/lincity_gui.dir/Event.cpp.o
/home/srandista/Downloads/lincity-ng/src/gui/Event.cpp: In constructor ‘Event::Event(SDL_Event&)’:
/home/srandista/Downloads/lincity-ng/src/gui/Event.cpp:57:31: error: cannot convert ‘float*’ to ‘int*’
   57 |             SDL_GetMouseState(&mousepos.x, &mousepos.y);
      |                               ^~~~~~~~~~~
      |                               |
      |                               float*
In file included from /usr/include/SDL2/SDL_events.h:35,
                 from /usr/include/SDL2/SDL.h:41,
                 from /home/srandista/Downloads/lincity-ng/src/gui/Event.hpp:21,
                 from /home/srandista/Downloads/lincity-ng/src/gui/Event.cpp:18:
/usr/include/SDL2/SDL_mouse.h:104:55: note:   initializing argument 1 of ‘Uint32 SDL_GetMouseState(int*, int*)’
  104 | extern DECLSPEC Uint32 SDLCALL SDL_GetMouseState(int *x, int *y);
      |                                                  ~~~~~^
gmake[2]: *** [src/gui/CMakeFiles/lincity_gui.dir/build.make:202: src/gui/CMakeFiles/lincity_gui.dir/Event.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:360: src/gui/CMakeFiles/lincity_gui.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

Since the error message pointed to event.cpp, I again tried to compile from commit before recent change in that file (cba172b) and that went fine, it finished with successful build.

If you need any additional info or logs, just let me know.

Thank you.

**Comment by Srandista** [comment]
Just to specify, I use gcc 11.4.0 + cmake 3.22.1 in my environment.

Also, when I replaced Event.cpp from the commit, that worked for me, I got the error on the same file as I did on my Raspberry Pi in separate issue (https://github.com/lincity-ng/lincity-ng/issues/144), just with more detailed output:

```[  4%] Building CXX object src/lincity/CMakeFiles/lincity_lib.dir/xmlloadsave.cpp.o
/home/srandista/Downloads/lincity-ng/src/lincity/xmlloadsave.cpp: In member function ‘void XMLloadsave::loadGlobals()’:
/home/srandista/Downloads/lincity-ng/src/lincity/xmlloadsave.cpp:892:103: warning: format ‘%d’ expects argument of type ‘int*’, but argument 3 has type ‘bool*’ [-Wformat=]
  892 |               if     (xml_tag == std::string("import_") + cname + "_enable") sscanf(xml_val.c_str(),"%d",&portConstructionGroup.tradeRule[c].take);
      |                                                                                                      ~^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                       |  |
      |                                                                                                       |  bool*
      |                                                                                                       int*
/home/srandista/Downloads/lincity-ng/src/lincity/xmlloadsave.cpp:893:103: warning: format ‘%d’ expects argument of type ‘int*’, but argument 3 has type ‘bool*’ [-Wformat=]
  893 |               else if(xml_tag == std::string("export_") + cname + "_enable") sscanf(xml_val.c_str(),"%d",&portConstructionGroup.tradeRule[c].give);
      |                                                                                                      ~^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                       |  |
      |                                                                                                       |  bool*
      |                                                                                                       int*
/home/srandista/Downloads/lincity-ng/src/lincity/xmlloadsave.cpp:902:9: error: expected primary-expression before ‘}’ token
  902 |         }
      |         ^
gmake[2]: *** [src/lincity/CMakeFiles/lincity_lib.dir/build.make:356: src/lincity/CMakeFiles/lincity_lib.dir/xmlloadsave.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:386: src/lincity/CMakeFiles/lincity_lib.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

**Comment by Srandista** [comment]
Also, I just find out, that I'm unable to run the latest pre-compiled binaries from the GitHub release page on 22.04, due to older version of glibc and glibcxx. Version 2.10.2 can run just fine. Is this to be expected?
