### PR TITLE
fix compile errors for older systems

### LINKED ISSUE #144: Compilation failed on Raspberry Pi
Hello.
I tried to compile latest build on my Raspberry Pi with Raspberry Pi OS basted on Debian Bookworm, but compilation failed on following step:

```[  4%] Building CXX object src/lincity/CMakeFiles/lincity_lib.dir/xmlloadsave.cpp.o
/home/srandista/Downloads/lincity-ng/src/lincity/xmlloadsave.cpp: In member function ‘void XMLloadsave::loadGlobals()’:
/home/srandista/Downloads/lincity-ng/src/lincity/xmlloadsave.cpp:902:9: error: expected primary-expression before ‘}’ token
  902 |         }
      |         ^
gmake[2]: *** [src/lincity/CMakeFiles/lincity_lib.dir/build.make:356: src/lincity/CMakeFiles/lincity_lib.dir/xmlloadsave.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:386: src/lincity/CMakeFiles/lincity_lib.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

Since the error message pointed to xmlloadsave.cpp, I tried to compile from commit before recent change in that file (d881eb2) and that went fine, it finished with successful build.

If you need any additional info or logs, just let me know.

Thank you.

### LINKED ISSUE #145: Compilation failed on Xubuntu 22.04
Hello.
I tried to compile latest build on Xubuntu 22.04, but compilation failed on following step:

```[  0%] Building CXX object src/gui/CMakeFiles/lincity_gui.dir/Event.cpp.o
/home/srandista/Downloads/lincity-ng/src/gui/Event.cpp: In constructor ‘Event::Event(SDL_Event&)’:
/home/srandista/Downloads/lincity-ng/src/gui/Event.cpp:57:31: error: cannot convert ‘float*’ to ‘int*’
   57 |             SDL_GetMouseState(&mousepos.x, &mousepos.y);
      |                               ^~~~~~~~~~~
      |                               |
      |                               float*
In file included from /usr/include/SDL2/SDL_events.h:35,
                 from /usr/include/SDL2/SDL.h:41,
                 from /home/srandista/Downloads/lincity-ng/src/gui/Event.hpp:21,
                 from /home/srandista/Downloads/lincity-ng/src/gui/Event.cpp:18:
/usr/include/SDL2/SDL_mouse.h:104:55: note:   initializing argument 1 of ‘Uint32 SDL_GetMouseState(int*, int*)’
  104 | extern DECLSPEC Uint32 SDLCALL SDL_GetMouseState(int *x, int *y);
      |                                                  ~~~~~^
gmake[2]: *** [src/gui/CMakeFiles/lincity_gui.dir/build.make:202: src/gui/CMakeFiles/lincity_gui.dir/Event.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:360: src/gui/CMakeFiles/lincity_gui.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
```

Since the error message pointed to event.cpp, I again tried to compile from commit before recent change in that file (cba172b) and that went fine, it finished with successful build.

If you need any additional info or logs, just let me know.

Thank you.

### PR DESCRIPTION
**Pull request by dbear496**
Fixes some compile-time errors on systems using older version of gcc and/or older version of sdl.

- Fixes #144.
- Fixes #145.
- Fixes bad parsing of bool in XML save file.
- Fixes up some includes.

### CODE REVIEW

**Comment by uafr** [comment]
Debian stable need the semicolon in xmlloadsave.cpp
